export const GETTING_STARTED_PATH = 'Getting Started.md';

export const GETTING_STARTED_CONTENT = [
	'# Welcome to Personal Notes',
	'',
	'Personal Notes is a private Markdown workspace that runs in your browser. Use it to organize study notes, code snippets, checklists, references, and screenshots without sending your local workspace anywhere.',
	'',
	'> This guide was created automatically the first time your local workspace was opened. You can edit, rename, or delete it like any other note.',
	'',
	'## Quick start',
	'',
	'1. Use the **+** menu next to Home to create a file or folder.',
	'2. Select a note in the sidebar and edit it directly.',
	'3. Use the **Save** button to persist your changes.',
	'4. Open an item menu to rename or delete files and folders.',
	'5. Press **Ctrl+K** to search your notes by title.',
	'',
	'## What you can write',
	'',
	'The editor supports the Markdown building blocks commonly used for study material:',
	'',
	'- Headings and paragraphs',
	'- **Bold**, *italic*, links, and inline `code`',
	'- Ordered, unordered, and task lists',
	'- Blockquotes and horizontal rules',
	'- Tables',
	'- Code blocks with syntax highlighting',
	'- Mathematical expressions',
	'- Images with captions',
	'',
	'### A checklist example',
	'',
	'- [x] Create a topic folder',
	'- [x] Write the first note',
	'- [ ] Review it later',
	'',
	'### A table example',
	'',
	'| Topic | Status | Next review |',
	'| --- | --- | --- |',
	'| Markdown | Learning | Tomorrow |',
	'| IndexedDB | Planned | Next week |',
	'',
	'### A code example',
	'',
	'```ts',
	"const note = 'Small notes are easier to review';",
	'console.log(note);',
	'```',
	'',
	'### A math example',
	'',
	'$$E = mc^2$$',
	'',
	'## Working with images',
	'',
	'Add screenshots through the image block or by pasting and dropping supported image files into the editor. PNG, JPEG, WebP, AVIF, and GIF files are accepted.',
	'',
	'Before storage, regular images are resized to a maximum dimension of 1280 pixels and converted to WebP when that produces a smaller file. GIF files remain unchanged to preserve animation.',
	'',
	'Images are stored as binary blobs in IndexedDB. The Markdown keeps only a local reference, so large Base64 strings do not inflate your notes.',
	'',
	'## Where your notes are stored',
	'',
	'Your local documents and images live in IndexedDB for this browser profile. They remain available after refreshing or reopening the application.',
	'',
	'**Important:** local notes are tied to this browser, profile, and device. Clearing site data or browser storage removes them. Keep important information backed up outside the browser.',
	'',
	'## Personalize the workspace',
	'',
	'Open Settings to change the editor appearance and theme. The sidebar works on desktop and mobile, and the search button provides quick access to every local note.',
	'',
	'You are ready to replace this guide with your own notes.'
].join('\n');
